// Generated by CoffeeScript 1.4.0
(function() {

  describe("Address Form", function() {
    jasmine.getFixtures().fixturesPath = 'javascript/spec/fixtures';
    beforeEach(function() {
      loadFixtures('address_form.html');
      this.invisible_form = $('#address-form');
      return this.address_form = new GetLeg.Views.AddressForm({
        el: this.invisible_form,
        collection: new GetLeg.Collections.LegislatorsCollection
      });
    });
    it("should be defined", function() {
      return expect(GetLeg.Views.AddressForm).toBeDefined();
    });
    it("should have the right element", function() {
      return expect(this.address_form.$el).toEqual(this.invisible_form);
    });
    it("should have a collection", function() {
      return expect(this.address_form.collection).toEqual(new GetLeg.Collections.LegislatorsCollection);
    });
    return describe("form submit", function() {
      it("should have a user-address input area", function() {
        return expect($('#user_address')).toBeDefined();
      });
      it("should allow us to the get value of the user_address", function() {
        return expect($('#user_address').val()).toEqual("");
      });
      return it("should allow us to click the submit button", function() {
        return expect($('#Submit')).toBeDefined();
      });
    });
  });

}).call(this);
