// Generated by CoffeeScript 1.4.0
(function() {

  describe("App namespace", function() {
    return it("should be defined", function() {
      return expect(GetLeg).toBeDefined();
    });
  });

}).call(this);
