// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  GetLeg.Models.AddressForm = (function(_super) {

    __extends(AddressForm, _super);

    function AddressForm() {
      return AddressForm.__super__.constructor.apply(this, arguments);
    }

    AddressForm.prototype.defaults = {
      lat: -40.12313,
      long: 111.12412,
      address: "916 South 1900 East SLC 84108"
    };

    AddressForm.prototype.url = function() {
      return "http://maps.googleapis.com/maps/api/geocode/json?address=" + this.get('address') + "&sensor=false";
    };

    AddressForm.prototype.parse = function(json) {
      this.set({
        lat: json.results[0].geometry.location.lat
      });
      return this.set({
        long: json.results[0].geometry.location.lng
      });
    };

    AddressForm.prototype.initialize = function() {
      var _this = this;
      this.fetch();
      return this.on('change:address', function() {
        return _this.fetch();
      });
    };

    return AddressForm;

  })(Backbone.Model);

}).call(this);
